### ISSUE TITLE
Collector never ending

### ISSUE THREAD

**Issue by BDT-4248** [miguelcollaco/eris-interactions#1]
Each time i use the collector, the `interaction` part work but not the `end`. i put  max time of 10000 but it doesnt seem to work at all. I used this:
``const options = { filter: int => int.data.custom_id == 'yes'), maxTime: 10000 };
const collector = new interactionCollector(ctx, await i.getOriginalMessage(), options);``
but it doesn't seem to end the collector after the maxTime

**Comment by miguelcollaco** [comment]
Hi!
First of all, thank you for using my code and reporting your issue.
I will look into it ASAP!

**Comment by BDT-4248** [comment]
did you find a solution/fix? because this is the only promising collector i can count on and it'd suck if there's none :/

**Comment by miguelcollaco** [comment]
@BDT-4248 Why are you passing three arguments to interactionCollector?

**Comment by BDT-4248** [comment]
according to the info i've read for this package, it says this:
`Setting up a listener:
new interactionCollector(client, message, options);`

**Comment by miguelcollaco** [comment]
![image](https://user-images.githubusercontent.com/65288220/231283685-7a5c9ea5-b17e-4d27-b808-fcaedfc0b19f.png)
You only need the message and options.

**Comment by miguelcollaco** [comment]
@BDT-4248 Hi!

After trying to use my package in a project I noticed that what you said is indeed correct, the client needs to be passed as the first argument.
I also looked into de code and discovered the reason why the collector wasn't ending.
I have just released a new version with all the bugs fixed and an updated README !
